### PR TITLE
closes #198, closes #181, closes #187

### LINKED ISSUE #181: Modify the unit class to implement the different commands and attributes.

### LINKED ISSUE #187: Modify the unit class to implement the movements of the units on the map.

### LINKED ISSUE #198: Modify the unit class to implement the attack commands.

### PR DESCRIPTION
**Pull request by paolovic**
More questions than actual code review:

Maybe I'm interpreting these tickets #198, #181, #187 too simple.

For #198 I used the following formula to compute the resulting health points:
attackDamage / victimDefense = hp Difference (which will be deducted from the victims HP)

I should implement some Logic, that as soon as the health of a victim unit is <=0 this unit is removed, right? (Didn't do it yet, became obvious to me just at this moment while I'm typing these lines)

Regarding #181 you basically did this on the frontend

Regarding #187 it's just unit.setPosition in my opinion.

Comments from your side are very welcome!
Thx guys!

### CODE REVIEW

**Review by apple00juice — APPROVED** [review]
Looks good, but why did you remove wait?

Example problem without wait:
Unit A does move and attack  so we call move then attack.
Unit B just moves we need to call move.

=> The game then does not know that unit B is also finished and thus can't end the turn.

With wait:
Unit A does move and attack so we call move then attack then wait.
Unit B just moves we need to call move then wait.

The game knows all units performed wait > turn ends > notify clients

**Review by luis-tm — COMMENTED** [review]
Why is unit_attack/victim_defense? It's not going to be very slow to kill an unit in this way? I thought it would be something like unit_attack - victim_defense.

**Comment by paolovic** [comment]
> Why is unit_attack/victim_defense? It's not going to be very slow to kill an unit in this way? I thought it would be something like unit_attack - victim_defense.

This was Alessio's proposal.

**Comment by apple00juice** [comment]
> Why is unit_attack/victim_defense? It's not going to be very slow to kill an unit in this way? I thought it would be something like unit_attack - victim_defense.

I wouldn't do "-", because if we would want to implement defense tile effects in the future, and the defense > attack, the unit would heal because newHP = oldHP - hpChange = oldHP - (unitAttack - victimdefense) = oldHP - unitAttack + victimdefense.

With the current numbers, yes, but they are random anyways and would need to be adjusted. If we set it to something in between 1-2 maybe 3 it wouldn't be that slow.

We could also do
newHP = oldHP - max(unitAttack - victimdefense, 0) 
if you like "-" more.

**Comment by paolovic** [comment]
> Looks good, but why did you remove wait?
> 
> Example problem without wait: Unit A does move and attack so we call move then attack. Unit B just moves we need to call move.
> 
> => The game then does not know that unit B is also finished and thus can't end the turn.
> 
> With wait: Unit A does move and attack so we call move then attack then wait. Unit B just moves we need to call move then wait.
> 
> => The game knows all units performed wait > turn ends > notify clients

Then I don't understand our current frontend implementation.
We click on a Unit, then we see the current range of traversable tiles. We click on a tile, then we say WAIT or CANCEL. WAIT means we move the selected unit to that tile and wait afterwards.
If another Unit is in our range we can click on that and attack that (which will also move our unit in front of the enemy I assume).

What do we need a separate "MOVE endpoint for, when we basically just execute WAIT (which will move the unit) and ATTACK (which will also move the unit). But we never just MOVE, do we?

(Maybe I just don't understand what you mean :D )

**Comment by luis-tm** [comment]
> > Why is unit_attack/victim_defense? It's not going to be very slow to kill an unit in this way? I thought it would be something like unit_attack - victim_defense.
> 
> I wouldn't do "-", because if we would want to implement defense tile effects in the future, and the defense > attack, the unit would heal because newHP = oldHP - hpChange = oldHP - (unitAttack - victimdefense) = oldHP - unitAttack + victimdefense.
> 
> With the current numbers, yes, but they are random anyways and would need to be adjusted. If we set it to something in between 1-2 maybe 3 it wouldn't be that slow.
> 
> We could also do newHP = oldHP - max(unitAttack - victimdefense, 0) if you like "-" more.

No no, it's perfect like this! I just wanted to understand it 😃

**Review by luis-tm — APPROVED** [review]

**Pull request merged**
