### PR TITLE
Feature create lobby and get lobby services

### LINKED ISSUE #143: Implement services to interact with the lobby class: create a lobby and get lobby.

### PR DESCRIPTION
**Pull request by apple00juice**
Changed user system to registered user and player
Implemented create lobby and get lobby service
- close #143

### CODE REVIEW

**Review by luis-tm — COMMENTED** [review]
Do we need to assign the teams when creating the lobby? The front needs to know this information to inform the 'team' column to display it on the view.

**Comment by apple00juice** [comment]
> Do we need to assign the teams when creating the lobby? The front needs to know this information to inform the 'team' column to display it on the view.

Yea, you are right. I need to add the field "team" to the LobbyGetDTO. And I will assign team 1 to the host, as default.
ty

**Comment by apple00juice** [comment]
> > Do we need to assign the teams when creating the lobby? The front needs to know this information to inform the 'team' column to display it on the view.
> 
> Yea, you are right. I need to add the field "team" to the LobbyGetDTO. And I will assign team 1 to the host, as default. ty

Implemented with last commit

**Comment by paolovic** [comment]
Give me some Hours, I'll give you feedback until tonight

**Comment by apple00juice** [comment]
Thank you both for reviewing it! 😄

**Pull request merged**
