### PR TITLE
send socket messages to public lobby view

### PR DESCRIPTION
**Pull request by luis-tm**
- Added code to send messages to the view of public lobbies when there is an update: a new lobby is created, a lobby changes its visibility, a player leaves a lobby.

### CODE REVIEW

**Review by paolovic — APPROVED** [review]
Ty!
But please wait with the merge until my branch is merged. otherwise I will have to resolve even more merge conflicts :D

**Comment by luis-tm** [comment]
> Ty! But please wait with the merge until my branch is merged. otherwise I will have to resolve even more merge conflicts :D

Sure! :)

**Review by apple00juice — APPROVED** [review]
Looks good! We could also add the message to add player (LobbyController ~Line 181)

**Comment by luis-tm** [comment]
> Looks good! We could also add the message to add player (LobbyController ~Line 181)

ah yes! I forgot to add it

**Pull request merged**
